### ISSUE TITLE
FileNotFoundError with coco mask

### ISSUE THREAD

**Issue by cinout** [dahyun-kang/ifsl#11]
Hi, 

Thank you for sharing your code. I have an issue here with accessing the "mask" of coco train/val samples. 

When I ran the training code, I received this error `FileNotFoundError: [Errno 2] No such file or directory: '../datasets/COCO2014/annotations/train2014/COCO_train2014_000000298475.png'`. It results from this part of code:

(line 205-210, fs-cs/data/coco.py)
``` 
def read_mask(self, name):
        mask_path = os.path.join(self.base_path, "annotations", name)
        mask = torch.tensor(
            np.array(Image.open(mask_path[: mask_path.index(".jpg")] + ".png"))
        )
        return mask
```

In my coco2014 dataset, under `annotations` subfolder, there are only 6 json files (e.g., captions_train2014.json), but your code assumes there should be image files (e.g., train2014/COCO_train2014_000000298475.png) under `annotations` subfolder. 

I am very confused here. Is there something wrong with my coco2014 folder structure？

Thank you. Waiting for your reply.

**Comment by dahyun-kang** [comment]
Hi

Sorry for the late reply and I hope you've already figured it out.
The original annotation and data structure follows [PFENet's implementation](https://github.com/dvlab-research/PFENet) which uses an annotation pre-processing parsing script from *.json to *.png.

You can find it [here](https://github.com/dvlab-research/PFENet/issues/20)

Have a good day! :slightly_smiling_face:
