### ISSUE TITLE
cannot import name 'reset' from 'pytorch_lightning.callbacks'

### ISSUE THREAD

**Issue by BokaiGu** [dahyun-kang/ifsl#12]
Im sorry to disturbe you. I am a novice. I follow the conda environment installation guide, but i still find it is hard to run the project. I also can not find any useful solution online.

**Comment by dahyun-kang** [comment]
Hi

I also experienced the same issue with a higher [pytorch-lightning](https://www.pytorchlightning.ai/) version.
Please downgrade pytorch-lightning lower than 1.7 at least.
Note that this code is built on pytorch-lightning==1.3.8

Thank you, have a good day! :slightly_smiling_face: 

Best, Dahyun
