### ISSUE TITLE
module 'common.utils' has no attribute 'mean'

### ISSUE THREAD

**Issue by Rongtao-Xu** [dahyun-kang/ifsl#2]
/ifsl/fs-s/model/asnet.py", line 138, in _shared_epoch_end
    avg_loss = utils.mean(self.average_meter.loss_buf)
AttributeError: module 'common.utils' has no attribute 'mean'

**Comment by dahyun-kang** [comment]
Hello Rongtao

That module is a simple avg function but it seems missing during refactoring.
I'll get back to you asap as I'm currently attending the conference to present this paper.
Thank you for the interest and see you soon. Have a great day! 😃

Best,
Dahyun
