### ISSUE TITLE
aslayer code problem?

### ISSUE THREAD

**Issue by WHL182** [dahyun-kang/ifsl#4]
out = torch.einsum('b g c t l, b g c t m -> b g t l m', q_out, k_out) ? is right?

**Comment by dahyun-kang** [comment]
Hello,

Yes, it is. What point do you think it isn't right?

Dahyun

**Comment by WHL182** [comment]
I think it may be " torch.einsum('b g c t l, b g c t m -> b g c l m', q_out, k_out)",

**Comment by dahyun-kang** [comment]
Ah I see, I believe I implemented it correctly as I designed.

At computing attention context like below:
`out = torch.einsum('b g c t l, b g c t m -> b g t l m', q_out, k_out)` 

* `t` is the flattened dimension for query image dimension (H_q * W_q)
* `l` is the flattened dimension for support image dimension of the target (refer page 5 footnote of the paper) embedding (H_s * W_s)
* `m` is the flattened dimension for support image dimension of the key embedding (H_s * W_s)

The AS layer operation is shared across all the `t`-dimensional query image points and computes attention between support-support (i.e. `l`-`m`) image dimension side. As the `t` dimension is reshaped to H_q x W_q at the end to produce a query image segmentation prediction, it should not disappear during operation. 🙂

I understand that this high-dimensional operation may cause much confusion but I hope my clarification would help.

Thank you, have a great day! 😃 

Dahyun

**Comment by WHL182** [comment]
ok, i will rethink it. thank you!
then, i have another question, this code "out = torch.einsum('b g c t l, b g c t m -> b g t l m', q_out, k_out)" need much memory?

**Comment by dahyun-kang** [comment]
Yes, take your time and feel free to reach out to me.

Well, it mainly depends on how big `H_s * W_s` is because the attention algorithm is still quadratic with H_s * W_s in terms of memory complexity.

In practice, one experiment takes up 24 GB with the batch size of 12, which is the default experimental setup stated in readme.md.

Hope it makes sense to you 😃 
Dahyun

**Comment by WHL182** [comment]
thank you, thank you very much! 😃
